### ISSUE TITLE
Wiki on installation

### ISSUE THREAD

**Issue by xe1os** [BrandonRS/get5-web#33]
Hi @BrandonRS,

It will be great if you mention the installation steps.

I would like to test and contribute on your get5 project.

Thanks.

**Comment by rush2sk8** [comment]
ok

**Comment by BrandonRS** [comment]
Honestly, this project is more a project for the specified collaborators to learn programming rather than something that is looking to be marketed/widely used. You can fork or follow along, but don't expect much in terms of speed or code quality.

**Comment by Andylovesmangos** [comment]
![image](https://user-images.githubusercontent.com/78506813/160617619-97c9ad6e-5f7e-4604-a2e9-98a47f2a465a.png)

I hecking love learning programming
